Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
AllCops:
  Exclude:
    - "vendor/**/*"
  UseCache: false
  TargetRubyVersion: 2.1
